name: Build Flutter APK

on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.x

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --release --dart-define=Server_Url=${{ secrets.SERVER_URL }} --dart-define=Redis_Url=${{ secrets.REDIS_URL }} --dart-define=Redis_Pass=${{ secrets.REDIS_PASS }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.repository.releases_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: MyApp-release.apk
          asset_content_type: application/vnd.android.package-archive
